<a href="https://colab.research.google.com/github/bannu053/Data_Science/blob/main/Pandas/Assignments/Netflix_Feature_Extraction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [17]:
import pandas as pd
import numpy as np

In [18]:
df=pd.read_csv("netflix_titles.csv.zip")
df.head(1)

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm..."

In [19]:
# 1) no of genres using feature extraction
# listed_in has multiple genres separated by commas
# 👉 Count number of genres per show

def Extration_genres(txt):
  count=1
  for i in txt:
    if(i == ","):
      count+=1
  return count

  # creating a new column for number of genres

df["no_of_genres"]=df["listed_in"].apply(Extration_genres)
df.head(5)

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description,no_of_genres
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm...",1
1,s2,TV Show,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t...",3
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN,"September 24, 2021",2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...,3
3,s4,TV Show,Jailbirds New Orleans,NaN,NaN,NaN,"September 24, 2021",2021,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo...",2
4,s5,TV Show,Kota Factory,NaN,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...,3

In [20]:
# Primary Genre
# Extract first genre from listed_in

def Extraction_primary_genre(txt):
  data=""
  for i in txt:
    if(i==","):
      break;
    data+=i
  return data

# creating a new column primary genre

df["primary_genre"]=df["listed_in"].apply(Extraction_primary_genre)
df.head(5)

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description,no_of_genres,primary_genre
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm...",1,Documentaries
1,s2,TV Show,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t...",3,International TV Shows
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN,"September 24, 2021",2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...,3,Crime TV Shows
3,s4,TV Show,Jailbirds New Orleans,NaN,NaN,NaN,"September 24, 2021",2021,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo...",2,Docuseries
4,s5,TV Show,Kota Factory,NaN,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...,3,International TV Shows

In [29]:
# # Duration Number From duration column
# Example: "90 min" → 90
#          "2 Seasons" → 2

def Extraction_duration(txt):
  data=""
  for i in txt:
    if(i==" "):
      break
    data+=i
  return data

  # create a new column duration with data type integer

df["duration_int"]=df["duration"].apply(Extraction_duration)
df.head(3)

TypeError: 'float' object is not iterable

problem in above code is:<br>
we had cells with nan which are basically float data type <br>
so we had 3 approches to crack it :
1) To handle missing values <br>
   if (pd.isna(txt))<br>
     return none<br>
2) convert to str
3) using regular expressions

In [39]:
# Duration Number From duration column
# Example: "90 min" → 90
#          "2 Seasons" → 2

def Extraction_duration(txt):
  txt = str(txt)
  data=""
  for i in txt:
    if(i==" "):
      break
    if(i=="n" or i=="N"):
      data="0"
    else:
     data+=i
  return data

  # create a new column duration with data type integer

df["duration_int"]=df["duration"].apply(Extraction_duration)
# now they are in string data type ; we have to change them to int
df["duration_int"]=df["duration_int"].astype(int)

df.head(3)

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description,no_of_genres,primary_genre,duration_int
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm...",1,Documentaries,90
1,s2,TV Show,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t...",3,International TV Shows,2
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN,"September 24, 2021",2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...,3,Crime TV Shows,1

In [41]:
# Content Type Flag
# Movie = 0, TV Show = 1
def extraction_Type_flag(txt):
  flag=""
  for i in txt:
    if(i=="M"):
      return 0
    else:
      return 1

# create a new column type flag

df["type_flag"]=df["type"].apply(extraction_Type_flag)
df.head(3)

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description,no_of_genres,primary_genre,duration_int,type_flag
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm...",1,Documentaries,90,0
1,s2,TV Show,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t...",3,International TV Shows,2,1
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN,"September 24, 2021",2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...,3,Crime TV Shows,1,1

In [62]:
# Actor Count From cast column
# 👉 Count number of actors per show

def extract_cast_count(txt):
    if pd.isna(txt):
        return 0

    return len(txt.split(","))

  # create new column cast count

df["cast_count"]=df["cast"].apply(extract_cast_count)
df.head(2)

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description,no_of_genres,primary_genre,duration_int,type_flag,cast_count
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm...",1,Documentaries,90,0,0
1,s2,TV Show,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t...",3,International TV Shows,2,1,19

In [63]:
from datetime import datetime

current_year = datetime.now().year
df["release_year"] =df["release_year"].fillna(0)
df["release_year"]=df["release_year"].astype(int)
df["content_age"] = current_year - df["release_year"]
df.head(2)

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description,no_of_genres,primary_genre,duration_int,type_flag,cast_count,content_age
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm...",1,Documentaries,90,0,0,6
1,s2,TV Show,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t...",3,International TV Shows,2,1,19,5